site_name: Lean Ethereum Specifications
site_description: Reference implementations of the Lean Ethereum protocol
site_author: Ethereum Foundation
site_url: https://leanethereum.github.io/lean-spec/

repo_name: leanEthereum/lean-spec
repo_url: https://github.com/leanEthereum/lean-spec
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature_annotations: true
            show_if_no_docstring: false
            inherited_members: true
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_section_style: google

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Home: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leanEthereum/lean-spec

copyright: |
  &copy; 2025 Ethereum Foundation
